# This file is responsible for running the below commands each commit
# on the TravisCI platform.

language: cpp

# A matrix build means that the following combinations of configurations
# are tested.
matrix:
  include:
      - os: osx  # Note: we pay extra for OSX for Travis
        compiler: clang
      - os: linux
        compiler: gcc
      - os: linux
        compiler: clang

# Email notifications
notifications:
  email:
    - matthew.szydagis@gmail.com

# Commands to install
install:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_INSTALL_PREFIX=${PWD} ..
  - make
  - make install

# Test commands
script:
  - ls
  - ./bin/execNEST 100 WIMP 100 1e-40 10 100,100,100 42
